### ISSUE TITLE
exception happened during program execution

### ISSUE THREAD

**Issue by stevexxs** [yumoxu/stocknet-code#3]
Hi,

I set up data, and run with default config,
but below err happened,
could you please help me how to fix it ?
Thanks !

Instructions for updating:
Use standard file APIs to delete files with this prefix.
2019-06-01 14:08:43,037 INFO 	Eval, eval loss: 1.6962803602218628, acc: 0.518293
2019-06-01 14:10:38,515 INFO 	iter: 280, batch loss: 1.7300004959106445, batch acc: 0.531250
2019-06-01 14:12:10,435 INFO 	Eval, eval loss: 1.60964834690094, acc: 0.507622
Traceback (most recent call last):
  File "/Users/liran/AI/stocknet-code/src/DataPipe.py", line 396, in batch_gen
    sample_dict = next(generators[gen_id])
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liran/AI/stocknet-code/src/DataPipe.py", line 418, in batch_gen
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Main.py", line 15, in <module>
    exe.train_and_dev()
  File "/Users/liran/AI/stocknet-code/src/Executor.py", line 148, in train_and_dev
    for train_batch_dict in train_batch_gen:
RuntimeError: generator raised StopIteration

**Comment by stevexxs** [comment]
the issue happened when using Python 3,7.
fix it by using python 3.6.
